// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: proto/movie-service.proto

package moviepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MoviePlatformClient is the client API for MoviePlatform service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MoviePlatformClient interface {
	CreateMovie(ctx context.Context, in *MovieRequest, opts ...grpc.CallOption) (*MovieResponse, error)
}

type moviePlatformClient struct {
	cc grpc.ClientConnInterface
}

func NewMoviePlatformClient(cc grpc.ClientConnInterface) MoviePlatformClient {
	return &moviePlatformClient{cc}
}

func (c *moviePlatformClient) CreateMovie(ctx context.Context, in *MovieRequest, opts ...grpc.CallOption) (*MovieResponse, error) {
	out := new(MovieResponse)
	err := c.cc.Invoke(ctx, "/MoviePlatform/CreateMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoviePlatformServer is the server API for MoviePlatform service.
// All implementations must embed UnimplementedMoviePlatformServer
// for forward compatibility
type MoviePlatformServer interface {
	CreateMovie(context.Context, *MovieRequest) (*MovieResponse, error)
	mustEmbedUnimplementedMoviePlatformServer()
}

// UnimplementedMoviePlatformServer must be embedded to have forward compatible implementations.
type UnimplementedMoviePlatformServer struct {
}

func (UnimplementedMoviePlatformServer) CreateMovie(context.Context, *MovieRequest) (*MovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMovie not implemented")
}
func (UnimplementedMoviePlatformServer) mustEmbedUnimplementedMoviePlatformServer() {}

// UnsafeMoviePlatformServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoviePlatformServer will
// result in compilation errors.
type UnsafeMoviePlatformServer interface {
	mustEmbedUnimplementedMoviePlatformServer()
}

func RegisterMoviePlatformServer(s grpc.ServiceRegistrar, srv MoviePlatformServer) {
	s.RegisterService(&MoviePlatform_ServiceDesc, srv)
}

func _MoviePlatform_CreateMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviePlatformServer).CreateMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MoviePlatform/CreateMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviePlatformServer).CreateMovie(ctx, req.(*MovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MoviePlatform_ServiceDesc is the grpc.ServiceDesc for MoviePlatform service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MoviePlatform_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MoviePlatform",
	HandlerType: (*MoviePlatformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMovie",
			Handler:    _MoviePlatform_CreateMovie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/movie-service.proto",
}
